export EDITOR=vim
export CODE_DIR=~/Code
export SETTINGS_DIR=$CODE_DIR/settings
export DOTFILES_DIR=$SETTINGS_DIR/dotfiles
export TOMCAT_HOME=$HOME/Code/apache-tomcat-9.0.19/

if [ -f ~/.profile ]; then
	source ~/.profile
fi

if [ -f ~/.work_settings ]; then
	source ~/.work_settings
fi

export CLICOLOR=1
export PS1='\033]0;$(basename $(dirname "$PWD"))/$(basename "$PWD")\007\[\e[1;37m\][\t]\]\[\e[1;33m\]\u\[\e[1;32m\]\[$bldblu\]$git_branch \[$bldgrn\]$git_head_tag \[$txtred\]$git_dirty\[$txtrst\] @\[\e[1;39m\] \W\[\e[1;38m\]\n\$ > '
export LSCOLORS='GxhxCxExBxdxhxFxgxHxcx'
alias ls='ls -lGFh -color'

alias shpr='cat ~/.bash_profile'

find_replace () {
	find . -type f -name "$1" -exec perl -i -pe"s/$2/$3/g" {} +
}
git_checkout_branch () {
	git checkout `git branch | sed -n $1p`
}
git_tag () {
	git tag $1_`date +%Y%m%d%H%M%S` && (git describe --tag --always | xargs git push origin)
}
source_dotfile () {
	link_dotfile $1
	if [[ $1 == "bash_profile" && -f ~/.bashrc ]]; then
		source ~/.bashrc
	else
		source ~/.$1
	fi
}
link_from_settings() {
	ln -sFf $SETTINGS_DIR/$1 $2
}
link_dotfile () {
	link_from_settings dotfiles/$1 ~/.$1
}
link_config () {
	link_from_settings configurations/$1 ~/.$1
}
edit_setfile () {
	vim $SETTINGS_DIR/$1
}
edit_dotfile () {
	vim $DOTFILES_DIR/$1
}
git_settings () {
	commit_msg="$1"
	ori_loc=$(pwd)
	cd $SETTINGS_DIR
	git add .
	git commit -m "$commit_msg"
	git pb
	cd $ori_loc
}
make_jsctags () {
	find . -type f -iregex ".*\.js$" -not -path "*/node_modules/*" -exec jsctags {} -f \; | sed '/^$/d' | sort > tags
}
uml_diagram () {
	java -jar ~/Code/tools/plantuml.jar -verbose $1
}
partial_rename_files () {
	local search="$1"
	local from=$2
	local to=$3
	local mode=$4
	if [[ ! -z $mode && $mode != "global" && $mode != "local" ]]; then
		echo "Mode must be global or local"
		return 1
	fi
	for file in $search; do
		if [[ ${mode:-global} = "global" ]]; then
			mv $file ${file//$from/$to}
		else
			mv $file ${file/$from/$to}
		fi
	done
}

alias fr=find_replace
alias gitcob=git_checkout_branch
alias tagtest='git_tag test_Btara'
alias tagstg='git_tag release_stg'
alias tagdev='git_tag release_stg'
alias tagrelease='git_tag release'
alias so='source_dotfile bash_profile'
alias sextras='[ -d $HOME/.extras ] && rm -r $HOME/.extras; link_dotfile extras'
alias se='edit_dotfile bash_profile'
alias sete=edit_setfile
alias dote=edit_dotfile
alias dotcp=link_dotfile
alias lfromset=link_from_settings
alias gitset=git_settings
alias dotso=source_dotfile
alias mkjstags=make_jsctags
alias uml=uml_diagram
alias prename=partial_rename_files
alias lconf=link_config
alias insecurechrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ignore-certificate-errors'

# some PHP/Apache things
alias apache='apachectl'

if [ -f /usr/local/share/bash-completion/bash_completion ]; then
	. /usr/local/share/bash-completion/bash_completion
fi

export GRAPHVIZ_DOT="/usr/local/bin/dot"

LC_ALL=en_us.UTF-8
export LANG="$LC_ALL"

# setting up rbenv
[[ -x rbenv ]] && eval "$(rbenv init -)"
# setting up direnv
[[ -x direnv ]] && eval "$(direnv hook bash)"

if [ -d $HOME/.extras/ ]; then
	for sourcefiles in $HOME/.extras/*; do
		source "$sourcefiles"
	done
fi

if command -v pyenv 1>/dev/null 2>&1; then
	eval "$(pyenv init -)"
fi

if [ -f ~/.iterm2_shell_integration.`basename $SHELL` ]; then
	source ~/.iterm2_shell_integration.`basename $SHELL`
fi

if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/btaratruhandarien/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
