# Added by Toolbox App
export PATH="$PATH:/Users/btaratruhandarien/Library/Application Support/JetBrains/Toolbox/scripts"
export CDPATH=$HOME

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

eval "$(rbenv init - $SHELL)"
