#!/bin/bash

# RUN ONLY WHEN PROVISION HAS BEEN RUN
# THIS IS TO BOOTSTRAP THE ENVIRONMENT TO WORK AS INTENDED

SETTINGS_DIR=$(cd $(dirname $0) && pwd)
TARGET_HOME="${2:-$HOME}"

# initialize bash profile
ln -sf "$SETTINGS_DIR"/dotfiles/bash_profile "$TARGET_HOME/.bash_profile"

# Copy bashrc
ln -sf "$SETTINGS_DIR"/dotfiles/bashrc "$TARGET_HOME/.bashrc"

# initialize zshrc
ln -sf "$SETTINGS_DIR"/dotfiles/zshrc "$TARGET_HOME/.zshrc"

# Copy all remaining dotfiles
ln -sf "$SETTINGS_DIR"/dotfiles/ctags "$TARGET_HOME/.ctags"
ln -sf "$SETTINGS_DIR"/dotfiles/eslintrc.json "$TARGET_HOME/.eslintrc.json"
ln -sf "$SETTINGS_DIR"/dotfiles/gitconfig "$TARGET_HOME/.gitconfig"
ln -sf "$SETTINGS_DIR"/dotfiles/npmrc "$TARGET_HOME/.npmrc"
ln -sf "$SETTINGS_DIR"/dotfiles/tern-project "$TARGET_HOME/.tern-project"
ln -sf "$SETTINGS_DIR"/dotfiles/vimrc "$TARGET_HOME/.vimrc"

# see: https://github.com/creationix/nvm#default-global-packages-from-file-while-installing
ln -sf "$SETTINGS_DIR"/installers/npm-default-packages "$TARGET_HOME/.nvm/default-packages"

# changing shell to bash install if available
if [[ -x '/bin/zsh' && '/bin/zsh' == $(which zsh) && '/bin/zsh' == $(echo $SHELL) ]]; then
	echo "default zsh is installed will not bootstrap another one"
elif [[ -x '/usr/local/bin/bash' && '/usr/local/bin/bash' != $(which bash) ]]; then
	sudo bash -c "echo '/usr/local/bin/bash' >> /etc/shells" && chsh -s /usr/local/bin/bash
fi

echo "All set up. Please re-login to the terminal"
