#!/bin/bash

## Install nvm
[ -d ~/.nvm ] && rm -rf ~/.nvm
git clone --depth 1 --branch master https://github.com/creationix/nvm.git ~/.nvm
cd ~/.nvm && . nvm.sh

nvm install --lts

# Install jsctags
npm install -g jsctags
