#!/bin/bash

SETTINGS_DIR="$1"
NVM_DIR="$HOME/.nvm"

if should "Install nvm?";
then
  [ -d ~/.nvm ] && rm -rf ~/.nvm
  git clone --depth 1 --branch master https://github.com/creationix/nvm.git ~/.nvm
  cd ~/.nvm && . nvm.sh
fi

if should "Redeploy default packages?";
then
  cp "$SETTINGS_DIR/nvm/default-packages" "$NVM_DIR/default-packages"
fi

if should "Install Node LTS?";
then
  . $NVM_DIR/nvm.sh
  nvm install --lts
fi
