#!/bin/bash

if should "Install Ruby (with rbenv)?"; then
	# Install ruby v3.1.2
	rbenv install 3.1.2

	# install bundler and ripper-tags
	rbenv local 3.1.2
	
	if should "Install default gems?"; then
		gem install bundler
		gem install ripper-tags
	fi
fi
