#!/bin/bash
# Installs vim realted plugins
# Note that $HOME/.vimrc NEEDS to be linked with the on in $SETTINGS_DIR/dotfiles/vimrc
# This means that this script should be run AFTER bootstrap

SETTINGS_DIR=$(get_settings_dir)

# stereokai
git clone https://github.com/gummesson/stereokai.vim.git ~/.vim/stereokai
cp -r ~/.vim/stereokai/colors/stereokai.vim ~/.vim/colors/
rm -rf ~/.vim/stereokai

# iceberg
git clone https://github.com/cocopon/iceberg.vim.git ~/.vim/iceberg
cp -r ~/.vim/iceberg/colors/iceberg.vim ~/.vim/colors/
rm -rf ~/.vim/iceberg

# Install vim plugins
[ ! -d ~/.vim/bundle/Vundle.vim ] && git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

vim +PluginInstall

# Setting up YCM
~/.vim/bundle/YouCompleteMe/./install.py --tern-completer --clang-completer

# Setting up tern_for_vim
cd ~/.vim/bundle/tern_for_vim/ && npm install

# put filetype.vim
echo "Copying filetype.vim to $HOME/.vim"
cp "$SETTINGS_DIR"/vim/filetype.vim $HOME/.vim/filetype.vim
